cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

catalog/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^search/$', views.search, name="search"),
    url(r'^(?P<id>[0-9]+)/$', views.item, name="item"),
    url(r'^category/(?P<slug>[\w-]+)/$', views.category, name="category"),
    url(r'^brand/(?P<slug>[\w-]+)/$', views.brand, name="brand"),
    url(r'^add_order/$', views.order, name="order"),

]

shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'', include("catalog.urls")),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^users/', include('user.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
]

catalog/models.py
from django.db import models
class CategoriesFirst(models.Model):
    name = models.CharField(max_length = 50, verbose_name = "Название раздела")
    slug = models.CharField(max_length = 50, verbose_name = "Ссылка")
    def __str__ (self):
        return self.name
    class Meta:
        verbose_name_plural = "Раздел"

class CategoriesSecond(models.Model):
    name = models.CharField(max_length = 50, verbose_name = "Название категории")
    slug = models.CharField(max_length = 50, verbose_name = "Ссылка")
    section = models.ForeignKey(CategoriesFirst)
    def __str__ (self):
        return self.name
    class Meta:
        verbose_name_plural = "Категория"

class Brand(models.Model):
    name = models.CharField(max_length = 50, verbose_name = "Название категории")
    slug = models.CharField(max_length = 50, verbose_name = "Ссылка")
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "Брэнды"

class Product(models.Model):
    name = models.CharField(max_length = 50, verbose_name = "Название товара")
    description = models.TextField(verbose_name = "Описание")
    brand = models.ForeignKey(Brand)
    size = models.CharField(max_length = 50, verbose_name = "Размер")
    compound = models.CharField(max_length = 100, verbose_name = "Состав")
    price = models.DecimalField(decimal_places = 2, max_digits = 6, verbose_name = "Цена")
    count = models.IntegerField(default = 0, verbose_name = "Количество")
    land = models.CharField(max_length = 50, verbose_name = "Страна производитель")
    image = models.ImageField(upload_to = 'img', verbose_name = "Изображение товара")
    category = models.ForeignKey(CategoriesSecond)
    views = models.IntegerField(default = 0, verbose_name = "Просмотры", blank = True)
    def __str__ (self):
        return self.name
    class Meta:
        verbose_name_plural = "Продукты"

class Order(models.Model):
    last_name = models.CharField(max_length = 256, verbose_name="Фамилия")
    first_name = models.CharField(max_length = 256, verbose_name="Имя")
    two_name = models.CharField(max_length = 256, verbose_name="Отчество")
    phone = models.CharField(max_length = 256, verbose_name="Фамилия")
    stat = models.CharField(max_length = 256, verbose_name="Город")
    street = models.CharField(max_length = 256, verbose_name="Улица")
    house = models.CharField(max_length = 256, verbose_name="Дом")
    index = models.CharField(max_length = 256, verbose_name="Индекс")
    att = models.TextField(verbose_name="Примечания")
    product = models.TextField(verbose_name="Товары")

    def __str__ (self):
        return self.last_name + " " + self.first_name + " " + self.two_name
    class Meta:
        verbose_name_plural = "Заказы"

catalog/views.py
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm
from .models import Product, CategoriesSecond, CategoriesFirst, Brand, Order
from cart.cart import Cart
from django.http import HttpResponseRedirect
import random
from django.db.models import Q
def index(request):
    brands = Brand.objects.all()[:15]
    popular = Product.objects.all().order_by('-views')[:15]
    products = Product.objects.all()

    categoryes = return_category()
    cart = Cart(request)
    context = {'products':products, 'category_1':categoryes['category_1'], 'category_2':categoryes['category_2'],
               'category_3':categoryes['category_3'], 'cart':cart, 'brands':brands, 'popular':popular}
    return render(request, "catalog/index.html", context)

def item(request, id):
    brands = Brand.objects.all()[:15]
    popular = Product.objects.all().order_by('-views')[:15]
    cart = Cart(request)
    randQuery = Product.objects.order_by('?')[:4]
    categoryes = return_category()
    item = get_object_or_404(Product, id = id)
    item.views += 1
    item.save()
    category = CategoriesSecond.objects.get(name = item.category)
    section = CategoriesFirst.objects.get(name = category.section)
    cart_product_form = CartAddProductForm()
    context = {'item':item, 'cart_product_form':cart_product_form, 'category': category, 'section':section,'category_1':categoryes['category_1'], 'category_2':categoryes['category_2'],
               'category_3':categoryes['category_3'], 'randquery':randQuery, 'cart':cart, 'brands':brands, 'popular':popular}
    return render(request, "catalog/item.html", context)

def category(request, slug):
    brands = Brand.objects.all()[:15]
    popular = Product.objects.all().order_by('-views')[:15]
    cart = Cart(request)
    category = CategoriesSecond.objects.get(slug = slug)
    section = CategoriesFirst.objects.get(name = category.section)
    products = Product.objects.filter(category = category)
    categoryes = return_category()
    context = {'category':category, 'products':products,'category_1':categoryes['category_1'], 'category_2':categoryes['category_2'],
               'category_3':categoryes['category_3'], 'section':section, 'cart':cart, 'brands':brands, 'popular':popular}
    return render(request, "catalog/catalog.html", context)

def brand(request, slug):
    brands = Brand.objects.all()[:15]
    popular = Product.objects.all().order_by('-views')[:15]
    brand = Brand.objects.get(slug = slug)
    products = Product.objects.filter(brand = brand)
    cart = Cart(request)
    categoryes = return_category()
    context = {'cart':cart, 'products' : products, 'brand' : brand, 'brands':brands, 'popular':popular}
    return render(request, "catalog/catalog.html", context)
def return_category():
    woman = CategoriesFirst.objects.get(name = "Женщинам")
    man = CategoriesFirst.objects.get(name = "Мужчинам")
    kid = CategoriesFirst.objects.get(name = "Детям")
    category_1 = CategoriesSecond.objects.filter(section = woman)
    category_2 = CategoriesSecond.objects.filter(section = man)
    category_3 = CategoriesSecond.objects.filter(section = kid)
    categoryes = {'category_1':category_1, 'category_2':category_2, 'category_3':category_3}
    return categoryes

def search(request):
    brands = Brand.objects.all()[:15]
    popular = Product.objects.all().order_by('-views')[:15]
    cart = Cart(request)
    categoryes = return_category()
    if request.method == "POST":
        q = request.POST['q']
        result = Product.objects.filter(Q(name__icontains=q) | Q(description__icontains=q) | Q(description__iexact=q) | Q(name__icontains=q.title()))
        context = {'result':result,'category_1':categoryes['category_1'], 'category_2':categoryes['category_2'],
                   'category_3':categoryes['category_3'], 'q' : q, 'cart':cart, 'brands':brands, 'popular':popular}
        return render(request, "catalog/search.html", context)
    else:
        context = {'category_1':categoryes['category_1'], 'category_2':categoryes['category_2'],
                   'category_3':categoryes['category_3'], 'cart':cart, 'brands':brands, 'popular':popular}
        return render(request, "catalog/search.html", context)

def order(request):
    brands = Brand.objects.all()[:15]
    popular = Product.objects.all().order_by('-views')[:15]
    products = Product.objects.all()
    categoryes = return_category()
    cart = Cart(request)
    context = {'products':products, 'category_1':categoryes['category_1'], 'category_2':categoryes['category_2'],
               'category_3':categoryes['category_3'], 'cart':cart, 'brands':brands, 'popular':popular}
    if request.method == "POST":
        order = Order()
        order.last_name = request.POST['last_name']
        order.first_name = request.POST['first_name']
        order.two_name = request.POST['two_name']
        order.phone = request.POST['phone']
        order.stat = request.POST['stat']
        order.street = request.POST['street']
        order.house = request.POST['house']
        order.index = request.POST['index']
        order.att = request.POST['att']
        order.product = request.POST['product']
        order.save()
        return render(request, "catalog/thank.html", context)

catalog/templates/catalog/catalog.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Каталог</title>
    <link rel="stylesheet" type="text/css" href="{% static "/catalog/css/style.css" %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static "catalog/js/jquery214min.js" %}"></script>
    <script src="{% static "catalog/js/scripts.js" %}"></script>
    <script src="{% static "catalog/js/unslider.js" %}"></script>

    <script>
        $(function() {
            $('.slider').unslider({
                animation: 'fade',
                autoplay: true,
                arrows: false,
                nav: true,
                delay: 5000,
                speed: 1000
            })
        })
    </script>
</head>
<body>
<div id="shop_main_body"></div>

<div class="shop_container">
    <header>
        <div class="top_links">
            <a href="#" class="pull-left hidden-xs hidden-sm">О компании</a><a href="#" class="pull-left hidden-xs hidden-sm">Доставка и оплата</a><a href="#" class="pull-left hidden-xs hidden-sm">Контакты</a>
            {% if user.is_authenticated %}<a class="pull-right" href="{% url "users:logout" %}">Выход</a> <a class="pull-right">Привет, {{user.username}} </a> {% else %}<a href="{% url "users:register" %}" class="pull-right">Вход / Регистрация </a>{% endif %}
        </div>
        <div class="col-sm-12 col-md-10 top_brown">
            <table>
                <tr>
                    <td class="brand"><h1><a href="/">avdey</a></h1></td>
                    <td class="search_block hidden-xs hidden-sm">
                      <form method='post' action="{% url 'search' %}">
                          {% csrf_token %}
                        <input type="text" name='q' id="search" placeholder="поиск...">
                        <input type="submit" value="найти" id="search_button">
                      </form>
                    </td>
                    <td class="phones">
                      375 29 8836989<span class="small">пн-пт 10:00-20:00, сб-вс 10:00-18:00</span><br>
                      375 25 5000884<span>Звони, заказывай</span>
                    </td>
                </tr>
            </table>
        </div>
        <a style="text-decoration:none;" href="{% url "cart:CartDetail" %}" class="col-md-2 hidden-xs hidden-sm basket_big text-center">
            <div class="img-basket"></div>
              Корзина ({{ cart.get_total_quantity }})
        </a>
        <div class="clearfix"></div>
        <ul class="top_menu">
            <li class="hidden-xs hidden-sm">
                <a href="#" class="can_open">Бренды</a>
                <div>
                    <ul class="pull-left">
                        <li><a href="#">Anskin</a></li>
                        <li><a href="#">Baviphat</a></li>
                        <li><a href="#">Club Clio</a></li>
                        <li><a href="#">Holika Holika</a></li>
                        <li><a href="#">Anskin</a></li>
                        <li><a href="#">Baviphat</a></li>
                        <li><a href="#">Club Clio</a></li>
                        <li><a href="#">Holika Holika</a></li>
                        <li><a href="#">Anskin</a></li>
                        <li><a href="#">Baviphat</a></li>
                        <li><a href="#">Club Clio</a></li>
                        <li><a href="#">Holika Holika</a></li>
                        <li><a href="#">Anskin</a></li>
                        <li><a href="#">Baviphat</a></li>
                        <li><a href="#">Club Clio</a></li>
                        <li><a href="#">Holika Holika</a></li>
                        <li><a href="#">Holika Holika</a></li>
                    </ul>
                    <img src="{% static "/catalog/" %}img/subcat_img.jpg">
                </div>
            </li>
            <li class="hidden-xs hidden-sm">
                <a href="#" class="can_open">Лучшее</a>
                <div>
                    <ul class="pull-left">
                        <li><a href="#">Anskin</a></li>
                        <li><a href="#">Baviphat</a></li>
                        <li><a href="#">Club Clio</a></li>
                        <li><a href="#">Holika Holika</a></li>
                        <li><a href="#">Anskin</a></li>
                        <li><a href="#">Baviphat</a></li>
                        <li><a href="#">Club Clio</a></li>
                        <li><a href="#">Holika Holika</a></li>
                        <li><a href="#">Anskin</a></li>
                        <li><a href="#">Baviphat</a></li>
                        <li><a href="#">Club Clio</a></li>
                        <li><a href="#">Holika Holika</a></li>
                        <li><a href="#">Anskin</a></li>
                        <li><a href="#">Baviphat</a></li>
                        <li><a href="#">Club Clio</a></li>
                        <li><a href="#">Holika Holika</a></li>
                        <li><a href="#">Holika Holika</a></li>
                    </ul>
                    <img src="{% static "/catalog/" %}img/subcat_img.jpg">
                </div>
            </li>
            <li class="hidden-xs hidden-sm"><a href="#">Джинсы</a></li>
            <li class="hidden-xs hidden-sm"><a href="#">Рубашки</a></li>
            <li class="hidden-xs hidden-sm"><a href="#">Пиджаки</a></li>

            <li class="hidden-md hidden-lg">
                <a href="#" class="can_open">Каталог</a>
                <div class="mobile_subcats">
                    <ul>
                        <li>
                            <a href="#" class="can_open">Бренды</a>
                            <div>
                                <ul>
                                    <li><a href="#">Anskin</a></li>
                                    <li><a href="#">Baviphat</a></li>
                                    <li><a href="#">Club Clio</a></li>
                                    <li><a href="#">Holika Holika</a></li>
                                    <li><a href="#">Anskin</a></li>
                                    <li><a href="#">Baviphat</a></li>
                                    <li><a href="#">Club Clio</a></li>
                                    <li><a href="#">Holika Holika</a></li>
                                    <li><a href="#">Anskin</a></li>
                                    <li><a href="#">Baviphat</a></li>
                                    <li><a href="#">Club Clio</a></li>
                                    <li><a href="#">Holika Holika</a></li>
                                    <li><a href="#">Anskin</a></li>
                                    <li><a href="#">Baviphat</a></li>
                                    <li><a href="#">Club Clio</a></li>
                                    <li><a href="#">Holika Holika</a></li>
                                    <li><a href="#">Holika Holika</a></li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a href="#" class="can_open">Поло</a>
                            <div>
                                <ul>
                                    <li><a href="#">Anskin</a></li>
                                    <li><a href="#">Baviphat</a></li>
                                    <li><a href="#">Club Clio</a></li>
                                    <li><a href="#">Holika Holika</a></li>
                                    <li><a href="#">Anskin</a></li>
                                    <li><a href="#">Baviphat</a></li>
                                    <li><a href="#">Club Clio</a></li>
                                    <li><a href="#">Holika Holika</a></li>
                                    <li><a href="#">Anskin</a></li>
                                    <li><a href="#">Baviphat</a></li>
                                    <li><a href="#">Club Clio</a></li>
                                    <li><a href="#">Holika Holika</a></li>
                                    <li><a href="#">Anskin</a></li>
                                    <li><a href="#">Baviphat</a></li>
                                    <li><a href="#">Club Clio</a></li>
                                    <li><a href="#">Holika Holika</a></li>
                                    <li><a href="#">Holika Holika</a></li>
                                </ul>
                            </div>
                        </li>
                        <li><a href="#">Джинсы</a></li>
                        <li><a href="#">Рубашки</a></li>
                        <li><a href="#">Костюмы</a></li>
                    </ul>
                </div>
            </li>
            <li class="hidden-md hidden-lg"><a href="#">О магазине</a></li>
            <li class="hidden-md hidden-lg pull-right"><a href="#" class="basket_mob">Корзина пуста</a></li>
            <li class="hidden-md hidden-lg pull-right"><a href="#" class="search"></a></li>
        </ul>
    </header>
    <div class="white_row">
        <div class="hidden-xs hidden-sm col-md-3">
          <ul class="catalog">
              <li class="can_open">
                  Женщинам
                  <ul>
                    {% for cat in category_1 %}
                      <li><a href="{% url "category" cat.slug %}">{{cat.name}}</a></li>
                    {% endfor %}
                  </ul>
              </li>
              <li class="can_open">
                  Мужчинам
                  <ul>
                    {% for cat in category_2 %}
                      <li><a href="{% url "category" cat.slug %}">{{cat.name}}</a></li>
                    {% endfor %}
                  </ul>
              </li>
              <li class="can_open">
                  Детям
                  <ul>
                    {% for cat in category_3 %}
                      <li><a href="{% url "category" cat.slug %}">{{cat.name}}</a></li>
                    {% endfor %}
                  </ul>
              </li>
          </ul>
        </div>
        <div class="col-sm-12 col-md-9">
            <ul class="breads">
                <li>{{section.name}}</li>
                <li>&nbsp;&nbsp;>&nbsp;&nbsp;<a href="{% url "category" category.slug %}">{{category.name}}</a></li>
            </ul>

            <section class="tovary_block">
                <h2>{{category.name}}</h2>
                <ul class="tovary_catalog">
                {% for product in products %}
                    <li>
                        <img src="{{product.image.url}}">
                        <p>{{product.name}}</p>
                        <div class="price">{{product.price}} <span>руб</span></div><a href="{% url 'item' product.id %}" class="more">Подробнее</a>
                    </li>
                {% empty %}
                Товары отсутствуют
                {% endfor %}
                </ul>
            </section>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

<footer>
    <div class="shop_container">
        <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-4 text-left links">
            <a href="#">О компании</a>
            <a href="#">Доставка и оплата</a>
            <a href="#">Контакты</a>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-4 col-md-push-4 text-right">
            <ul class="soc">
                <li><a href="#" target="_blank"><img src="{% static "/catalog/" %}img/soc_vk.png"></a></li>
                <li><a href="#" target="_blank"><img src="{% static "/catalog/" %}img/soc_ok.png"></a></li>
                <li><a href="#" target="_blank"><img src="{% static "/catalog/" %}img/soc_fb.png"></a></li>
                <li><a href="#" target="_blank"><img src="{% static "/catalog/" %}img/soc_tw.png"></a></li>
                <li><a href="#" target="_blank"><img src="{% static "/catalog/" %}img/soc_gp.png"></a></li>
                <li><a href="#" target="_blank"><img src="{% static "/catalog/" %}img/soc_mail.png"></a></li>
            </ul>
        </div>
        <div class="clearfix hidden-lg hiddem-md"></div>
        <div class="col-sm-12 col-md-4 col-md-pull-4 text-center">
            <ul class="pays">
                <li><a href="#" target="_blank"><img src="{% static "/catalog/" %}img/qiwi.png"></a></li>
                <li><a href="#" target="_blank"><img src="{% static "/catalog/" %}img/visa.png"></a></li>
                <li><a href="#" target="_blank"><img src="{% static "/catalog/" %}img/webmoney.png"></a></li>
                <li><a href="#" target="_blank"><img src="{% static "/catalog/" %}img/yandex_money.png"></a></li>
            </ul>
            <!--p>&copy; 2016 www.site.ru<br>Copyright: Ali Sayed. All Rights Reserved.</p-->
        </div>
        <div class="clearfix"></div>
        </div>
    </div>
</footer>
</body>
</html>